swagger: "2.0"
info:
  description: This is the swagger file for the forum server
  version: "1.0.0"
  title: Forum REST API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /echo/{word}:
    get:
      operationId: forum.echo
      tags:
        - forum
      summary: return the text that is passed
      description: echo text
      parameters:
        - name: word
          in: path
          type: string
          description: input word
          required: true
      responses:
        200:
          description: echo the word
          schema:
            type: string
  /health:
    get:
      tags: [Health]
      operationId: forum.health
      summary: Health Check
      responses:
        '200':
          description: Status message from server describing current health            