swagger: "2.0"
info:
  description: This is the swagger file for the forum server
  version: "1.0.0"
  title: Forum REST API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /echo/{word}:
    get:
      operationId: forum.echo
      tags:
        - forum
      summary: return the text that is passed
      description: echo text
      parameters:
        - name: word
          in: path
          type: string
          description: input word
          required: true
      responses:
        200:
          description: echo the word
          schema:
            type: string
  /message:
    get:
      operationId: forum.read_all
      tags:
        - forum
      summary: Read the entire set of messages
      description: Read the entire set of messages
      responses:
        200:
          description: read messages
          schema:
            type: array
            items:
              properties:
                message_id:
                  type: string
                  description: Id of the message
                name:
                  type: string
                  description: name of the person
                text_entry:
                  type: string
                  description: Content of message
                timestamp:
                  type: string
                  description: Creation timestamp of the message
    post:
      operationId: forum.create
      tags:
        - forum
      summary: Create a post
      description: Create a new post
      parameters:
        - name: post
          in: body
          description: post to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: name of person
              text_entry:
                type: string
                description: body of post
      responses:
        201:
          description: Successfully created post
          schema:
            properties:
              person_id:
                type: string
                description: Id of the post
              name:
                type: string
                description: name of the person
              text_entry:
                type: string
                description: message body
              timestamp:
                type: string
                description: Creation/Update timestamp of the post
  /health:
    get:
      tags: [Health]
      operationId: forum.health
      summary: Health Check
      responses:
        '200':
          description: Status message from server describing current health            